from enum import IntEnum


class AnnotType(IntEnum):
    PDF_ANNOT_TEXT = 0
    PDF_ANNOT_LINK = 1  # <=== Link object in PyMuPDF
    PDF_ANNOT_FREE_TEXT = 2
    PDF_ANNOT_LINE = 3
    PDF_ANNOT_SQUARE = 4
    PDF_ANNOT_CIRCLE = 5
    PDF_ANNOT_POLYGON = 6
    PDF_ANNOT_POLY_LINE = 7
    PDF_ANNOT_HIGHLIGHT = 8
    PDF_ANNOT_UNDERLINE = 9
    PDF_ANNOT_SQUIGGLY = 10
    PDF_ANNOT_STRIKE_OUT = 11
    PDF_ANNOT_REDACT = 12
    PDF_ANNOT_STAMP = 13
    PDF_ANNOT_CARET = 14
    PDF_ANNOT_INK = 15
    PDF_ANNOT_POPUP = 16
    PDF_ANNOT_FILE_ATTACHMENT = 17
    PDF_ANNOT_SOUND = 18
    PDF_ANNOT_MOVIE = 19
    PDF_ANNOT_RICH_MEDIA = 20
    PDF_ANNOT_WIDGET = 21  # <=== Widget object in PyMuPDF
    PDF_ANNOT_SCREEN = 22
    PDF_ANNOT_PRINTER_MARK = 23
    PDF_ANNOT_TRAP_NET = 24
    PDF_ANNOT_WATERMARK = 25
    PDF_ANNOT_3D = 26
    PDF_ANNOT_PROJECTION = 27
    PDF_ANNOT_UNKNOWN = -1
